### Create Todo
POST http://localhost:8080/createTodo
Content-Type: application/json

{
  "id": "RandomID",
  "name": "Name of Todo",
  "desc": "Desc of Todo",
  "dueDate": "2023-11-28",
  "completionDate": "2023-11-30",
  "folder": "hvadlfh36497340hiusdh923",
  "priority": "HIGH"
}

### Read Todo
GET http://localhost:8080/readTodo/RandomID

### Update Todo
PUT http://localhost:8080/updateTodo/RandomID
Content-Type: application/json

{
  "id": "RandomID",
  "name": "Name of Todo",
  "desc": "",
  "dueDate": "2023-11-28",
  "completionDate": "2023-11-30",
  "folder": "hvadlfh36497340hiusdh923",
  "priority": "HIGH"
}

### Delete Todo
DELETE http://localhost:8080/deleteTodo/RandomID